Form/DataTransformer/EntityToIntTransformer.php
<?php

namespace Tisseo\CoreBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Doctrine\Common\Persistence\ObjectManager;

class EntityToIntTransformer implements DataTransformerInterface
{
    /**
     * @var \Doctrine\Common\Persistence\ObjectManager
     */
    private $om;
    private $entityClass;
    private $entityType;
    private $entityRepository;

    /**
     * @param ObjectManager $om
     */
    public function __construct(ObjectManager $om)
    {
        $this->om = $om;
    }

    /**
     * @param mixed $entity
     *
     * @return int
     */
    public function transform($entity)
    {
        // Modified from comments to use instanceof so that base classes or interfaces can be specified
        if (null === $entity || !$entity instanceof $this->entityClass) {
            return '';
        }

        return $entity->getId();
    }

    /**
     * @param mixed $id
     *
     * @throws \Symfony\Component\Form\Exception\TransformationFailedException
     *
     * @return mixed|object
     */
    public function reverseTransform($id)
    {
        if (!$id) {
            return null;
        }

        $entity = $this->om->getRepository($this->entityRepository)->findOneBy(array('id' => $id));

        if (null === $entity) {
            throw new TransformationFailedException(sprintf(
                'A %s with id "%s" does not exist!',
                $this->entityType,
                $id
            ));
        }

        return $entity;
    }

    public function setEntityType($entityType)
    {
        $this->entityType = $entityType;
    }

    public function setEntityClass($entityClass)
    {
        $this->entityClass = $entityClass;
    }

    public function setEntityRepository($entityRepository)
    {
        $this->entityRepository = $entityRepository;
    }
}

Form/Type/DatepickerType.php
<?php

namespace Tisseo\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DatepickerType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'format' => 'dd/MM/yyyy',
                'widget' => 'single_text'
            )
        );
    }

    public function getParent()
    {
        return 'date';
    }

    public function getName()
    {
        return 'tisseo_datepicker';
    }
}

Form/Type/DatetimepickerType.php
<?php

namespace Tisseo\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DatetimepickerType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'format' => 'dd/MM/yyyy HH:mm',
                'widget' => 'single_text'
            )
        );
    }

    public function getParent()
    {
        return 'datetime';
    }

    public function getName()
    {
        return 'tisseo_datetimepicker';
    }
}

Form/Type/EmailType.php
<?php

namespace Tisseo\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EmailType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'widget' => 'single_text'
            )
        );
    }

    public function getParent()
    {
        return 'email';
    }

    public function getName()
    {
        return 'tisseo_email';
    }
}

Form/Type/PasswordType.php
<?php

namespace Tisseo\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PasswordType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'widget' => 'single_text'
            )
        );
    }

    public function getParent()
    {
        return 'password';
    }

    public function getName()
    {
        return 'tisseo_password';
    }
}

Form/Type/TelType.php
<?php

namespace Tisseo\CoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TelType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'widget' => 'single_text'
            )
        );
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'tisseo_tel';
    }
}

Controller/CoreController.php
<?php

namespace Tisseo\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

abstract class CoreController extends Controller
{
    /**
     * Checking a request is sent from AJAX call with specified HTTP method
     *
     * @param Request $request
     * @param string  $method
     */
    protected function isAjax(Request $request, $method = Request::METHOD_GET)
    {
        if (!($request->isXmlHttpRequest() && $request->isMethod($method))) {
            throw $this->createAccessDeniedException();
        }
    }

    /**
     * Adding an error message to the session's flash bag
     *
     * @param string $error
     */
    protected function addFlashException($error)
    {
        $this->addFlash(
            'danger',
            $this->get('translator')->trans(
                'tisseo.flash.error.exception',
                array('%error%' => $error),
                'messages'
            )
        );
    }

    /**
     * Preparing a JsonResponse
     *
     * @param array $data
     * @param int   $statusCode
     */
    protected function prepareJsonResponse($data = array(), $statusCode = Response::HTTP_OK)
    {
        $response = new JsonResponse();
        $response->setData($data);
        $response->setStatusCode($statusCode);

        return $response;
    }
}

Controller/ExportController.php
<?php

namespace Tisseo\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ExportController extends Controller
{
    /**
     * Exporting a CSV file using an entity manager
     * The entity manager have to provide a getCsvExport function.
     *
     * @param string $service
     */
    public function exportCsvAction($service, $option)
    {
        $manager = $this->get($service);

        if (!is_callable(array($manager, 'getCsvExport'))) {
            throw new \Exception('The service used for CSV export have to provide an export function');
        }
        $response = new StreamedResponse();
        list($content, $filename) = empty($option) ? $manager->getCsvExport() : $manager->getCsvExport($option);

        $response->setCallback(function () use ($content) {
            $handle = fopen('php://output', 'w+');
            fwrite($handle, "\xEF\xBB\xBF"); // adds BOM utf8 fox Excel

            foreach ($content as $index => $row) {
                if ($index == 0) {
                    fputcsv($handle, array_keys($row), ';');
                }

                $csvRow = array();
                foreach ($row as $attribute) {
                    if ($attribute instanceof \Datetime) {
                        $csvRow[] = $attribute->format('Y-m-d');
                    } elseif (is_object($attribute)) {
                        if (is_callable(array($attribute, '__toString'))) {
                            $csvRow[] = $attribute;
                        } elseif (is_callable(array($attribute, 'getId'))) {
                            $csvRow[] = $attribute->getId();
                        } else {
                            $csvRow[] = '#error';
                        }
                    } else {
                        $csvRow[] = $attribute;
                    }
                }
                fputcsv($handle, $csvRow, ';');
            }

            fclose($handle);
        });

        $response->setStatusCode(200);
        $response->headers->set('Content-Type', 'application/force-download');
        //$response->headers->set('')
        $response->headers->set('Content-Disposition', 'attachment; filename="'.$filename.'.csv"');

        return $response;
    }
}

Resources/views/Form/fields.html.twig
{% block datepicker_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            {%  set attr = attr|merge({'class': ((attr.class|default('') ~ ' form-control')|trim)}) %}
            <input type="text"  data-provide="datepicker" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endspaceless %}
{% endblock datepicker_widget %}

{% block datetimepicker_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            {%  set attr = attr|merge({'class': ((attr.class|default('') ~ ' form-control')|trim)}) %}
            <input type="text"  data-provide="datetimepicker" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endspaceless %}
{% endblock datetimepicker_widget %}

{% block form_errors %}
    {% spaceless %}
        {% if errors is not empty %}
            {% if not form.parent %}
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <ul>
            {% else %}
                    <ul class="help-block">
            {% endif %}
                {% for error in errors %}
                    <li>{{
                        error.messagePluralization is null
                            ? error.message|trans(error.messageParameters)
                            : error.message|transchoice(error.messagePluralization, error.messageParameters)
                    }}</li>
                {% endfor %}
            </ul>
            {% if not form.parent %}
                </div>
            {% endif %}
        {% endif %}
    {% endspaceless %}
{% endblock %}

{% block button_widget %}
    {% set attr = attr|merge({class: (attr.class|default('btn-default') ~ ' btn')|trim}) %}
    {%- if attr['picto-left'] is not null -%}
        {%  set picto_l = attr['picto-left'] ~ ' ' %}
    {%- else %}
        {%  set picto_l = '' -%}
    {%- endif %}
    {%- if attr['picto-right'] is not null -%}
        {%  set picto_r = ' ' ~ attr['picto-right'] %}
    {%- else %}
        {%  set picto_r = '' %}
    {%- endif -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
                '%name%': name,
                '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}

    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ picto_l|raw }}{{ label|trans({}, translation_domain)|raw }}{{ picto_r|raw }}</button>
{% endblock button_widget %}

{% block tisseo_email_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
            {%  set attr = attr|merge({'class': ((attr.class|default('') ~ ' form-control')|trim)}) %}
            <input type="email"  {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endspaceless %}
{% endblock %}

{% block tisseo_password_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            {%  set attr = attr|merge({'class': ((attr.class|default('') ~ ' form-control')|trim)}) %}
            <input type="password"  {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endspaceless %}
{% endblock %}

{% block tisseo_tel_widget %}
    {% spaceless %}
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></span>
            {%  set attr = attr|merge({'class': ((attr.class|default('') ~ ' form-control')|trim)}) %}
            <input type="tel"  {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
        </div>
    {% endspaceless %}
{% endblock %}

Resources/views/Form/noErrorMessagesFields.html.twig
{% block form_errors %}
{% spaceless %}
    {% if errors is not empty %}
    {% endif %}
{% endspaceless %}
{% endblock %}

Resources/views/base.html.twig
{% extends "::base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets 'bundles/tisseocore/css/main.css'
                   filter='cssrewrite' output='css/tisseo_core.css' %}
        <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
    {% endstylesheets %}
    {% stylesheets 'bundles/bootstrapcolorpicker/css/bootstrap-colorpicker.min.css'
            filter='cssrewrite' %}
         <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
    {% endstylesheets %}
    {% stylesheets 'bundles/tisseocore/css/select2.min.css'
        filter='cssrewrite' output='css/select2.min.css' %}
        <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
    {% endstylesheets %}
    {% stylesheets 'bundles/tisseocore/css/select2-bootstrap.css'
        filter='cssrewrite' output='css/select2-bootstrap.min.css' %}
        <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
    {% endstylesheets %}
{% endblock %}

{% block head_config %}
    {{ parent() }}
    {% include 'TisseoCoreBundle::config.js.html.twig' %}
{% endblock %}

{% block navbar_brand %}{% endblock %}
{% block root_breadcrumb %}{% endblock %}

{% block body %}
    {% block subheader %}
    {% endblock %}
    {% block container %}
    {% endblock %}
{% endblock %}

Resources/views/centered_form.html.twig
{% extends "TisseoCoreBundle::container.html.twig" %}
{% set width = width is empty ? 10 : width %}
{% set offset = (12 - width)/2 %}

{% block main_content %}
    <div class="form-panel col-md-{{ width }} col-md-offset-{{ offset }}" role="main">
        {% block pre_header %}{% endblock %}
        <h1>{% block list_title %}{{ pageTitle|trans }}{% endblock %}</h1>
        {% block header_content %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
{% endblock %}

Resources/views/config.js.html.twig
<script>
requirejs.config({
    config: {
        i18n: {
            locale: "{{ app.request.locale }}"
        }
    },
    urlArgs: '{{ assets_version }}',
    paths: {
        'bootbox':                              'components/bootbox/bootbox',
        'leaflet':                              'components/leaflet/js/leaflet.min',
        'jquery_ui_draggable':                  'components/jquery-ui/ui/minified/jquery.ui.draggable.min',
        'jquery_ui_droppable':                  'components/jquery-ui/ui/minified/jquery.ui.droppable.min',
        'jquery_ui_sortable':                   'components/jquery-ui/ui/minified/jquery.ui.sortable.min',
        'bootstrap-colorpicker':                'bundles/bootstrapcolorpicker/js/bootstrap-colorpicker',
        'chartjs':                              'bundles/tisseocore/js/chart.min',
        'jquery/textfill':                      'bundles/tisseocore/js/jquery.textfill.min',
        'jquery/datatables':                    'bundles/tisseocore/js/jquery.dataTables.min',
        'smalot/bootstrap-datetimepicker':      'bundles/tisseocore/js/bootstrap-datetimepicker.min',
        'smalot/bootstrap-datetimepicker/fr':   'bundles/tisseocore/js/bootstrap-datetimepicker.fr',
        'turf':                                 'bundles/tisseocore/js/leaflet/turf.min',
        'select2' :                             'bundles/tisseocore/js/select2/select2.min',
        'core/textfill':                        'bundles/tisseocore/js/textfill',
        'core/form':                            'bundles/tisseocore/js/form',
        'core/moment':                          'bundles/tisseocore/js/moment',
        'core/datatables':                      'bundles/tisseocore/js/datatables',
        'core/collection':                      'bundles/tisseocore/js/collection',
        'core/improved-collection':             'bundles/tisseocore/js/improved-collection',
        'core/leaflet_utils':                   'bundles/tisseocore/js/leaflet/leaflet_utils',
        'core/map':                             'bundles/tisseocore/js/leaflet/map',
        'core/autocomplete':                    'bundles/tisseocore/js/autocomplete',
        'core/select-to-hidden':                'bundles/tisseocore/js/select-to-hidden',
        'core/confirm':                         'bundles/tisseocore/js/confirm',
        'core/compare-date':                    'bundles/tisseocore/js/compare-date',
        'core/dt-checkboxes':                   'bundles/tisseocore/js/dt-checkboxes',
        'core/toggle-rows':                     'bundles/tisseocore/js/toggle_rows',
        'core/select2' :                        'bundles/tisseocore/js/core-select2',
    },
    shim: {
        'bootbox': {
            deps: ['bootstrap']
        },
        'jquery/textfill': {
            deps: ['jquery']
        },
        'jquery/datatables': {
            deps: ['jquery']
        },
        'core/textfill': {
            deps: ['jquery/textfill']
        },
        'core/datatables': {
            deps: ['jquery/datatables', 'jquery/textfill', 'core/moment']
        },
        'core/leaflet_utils': {
            deps: ['jquery', 'turf', 'leaflet']
        },
        'core/map': {
            deps: ['jquery', 'leaflet']
        },
        jquery_ui_droppable: {
            deps: ['jquery', 'jquery_ui_core', 'jquery_ui_mouse', 'jquery_ui_widget'],
            exports: "jQuery"
        },
        jquery_ui_draggable: {
            deps: ['jquery', 'jquery_ui_core', 'jquery_ui_mouse', 'jquery_ui_widget'],
            exports: "jQuery"
        },
        jquery_ui_sortable: {
            deps: ['jquery', 'jquery_ui_core', 'jquery_ui_mouse', 'jquery_ui_widget'],
            exports: "jQuery"
        },
        'smalot/bootstrap-datetimepicker': {
            deps: ['bootstrap']
        },
        'smalot/bootstrap-datetimepicker/fr': {
            deps: ['smalot/bootstrap-datetimepicker']
        },
        'bootstrap-colorpicker': {
            deps: ['jquery']
        },
        'core/autocomplete': {
            deps: ['jquery_ui_autocomplete']
        },
        'core/select-to-hidden': {
            deps: ['jquery']
        },
        'core/delete-confirm': {
            deps: ['jquery', 'bootbox']
        },
        'core/select2': {
            deps: ['select2']
        }
    },
    deps: ['utils', 'jquery', 'core/form'],
    packages: [
        {
            name: "codemirror",
            location: "assets/vendor/codemirror",
            main: "lib/codemirror"
        }
    ]
});
</script>

Resources/views/container.html.twig
{% extends bundle ~ "::base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/bmatznerfontawesome/css/font-awesome.min.css') }}" />
    {% if datatable %}
        {% stylesheets 'bundles/tisseocore/css/jquery.dataTables.min.css'
                       filter='cssrewrite' output='css/datatables.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
    {% if smoothness %}
        {% stylesheets 'components/jquery-ui/themes/smoothness/jquery-ui.css'
                       filter='cssrewrite' output='css/smoothness.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
    {% if leaflet %}
        {% stylesheets 'components/leaflet/css/leaflet.css'
                       filter='cssrewrite' output='css/leaflet.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
    {% if datetimepicker %}
        {% stylesheets 'bundles/tisseocore/css/bootstrap-datetimepicker.min.css'
                       filter='cssrewrite' output='css/bootstrap-datetimepicker.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
    {% if codemirror %}
        {% stylesheets 'assets/vendor/codemirror/lib/codemirror.css'
                        filter='cssrewrite' output='css/codemirror.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
{% endblock %}

{% block container %}
    <div class="row">
        {% block main_content %}
            <div class="col-md-12" role="main">
                {% block pre_header %}{% endblock %}
                <h1>{% block list_title %}{{ pageTitle|trans }}{% endblock %}</h1>
                {% block header_content %}{% endblock %}
                {% block content %}{% endblock %}
            </div>
        {% endblock %}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if leaflet %}
        <script>
            var stop_icon_pin_url = "{{ asset('bundles/tisseocore/images/stop-icon.png') }}";
            var stop_icon_circle_url = "{{ asset('bundles/tisseocore/images/stop-icon-circle.png') }}";
        </script>
    {% endif %}
{% endblock %}

Resources/views/container_and_menu.html.twig
{% extends bundle ~ "::base.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    {% if datatable %}
        {% stylesheets 'bundles/tisseocore/css/jquery.dataTables.min.css'
                       filter='cssrewrite' output='css/datatables.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
    {% if smoothness %}
        {% stylesheets 'components/jquery-ui/themes/smoothness/jquery-ui.css'
                       filter='cssrewrite' output='css/smoothness.css' %}
            <link rel="stylesheet" href="{{ asset_url }}?{{ assets_version }}" />
        {% endstylesheets %}
    {% endif %}
{% endblock %}

{% set left_menu_html %}
{% endset %}

{% block container %}
<div class="row">
    {% block main_content %}
        <h1>{% block list_title %}{{ pageTitle|trans }}{% endblock %}</h1>
    {% endblock %}
</div>
{% endblock %}

Resources/views/datatable_list.html.twig
{% extends "TisseoCoreBundle::container.html.twig" %}
{% set datatable = true %}

{% block content %}
<table class="table {% if not empty %}datatable {% endif %}{% block table_classes -%}table-hover{% endblock %}">
    <thead>
    {% block table_head_tr %}{% endblock %}
    <tr>
        {% block table_head %}{% endblock %}
    </tr>
    </thead>
    <tbody>
    {% block table_body %}{% endblock %}
    </tbody>
</table>
{% block list_pagination %}{% endblock %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if not empty %}
        {% if not paginate %}
            {% set paginate = 'false' %}
        {% endif %}
        {% if not margin %}
            {% set margin = '0' %}
        {% endif %}
        {% if not processing %}
            {% set processing = 'false' %}
        {% endif %}
        {% if not serverSide %}
            {% set serverSide = 'false' %}
        {% endif %}
        {% if not iDisplayLength %}
            {% set iDisplayLength = 100 %}
        {% endif %}
        {% if not caseInsensitive %}
            {% set caseInsensitive = 'true' %}
        {% endif %}
        {% if not activateSearch %}
            {% set activateSearch = 'true' %}
        {% endif %}

        <script>
            require(['core/datatables'], function () {
                datatable({
                    'bPaginate': {{ paginate }},
                    'margin': {{ margin }},
                    'iDisplayLength': {{ iDisplayLength }},
                    'processing': {{ processing }},
                    'serverSide': {{ serverSide }},
                    'bFilter': {{ activateSearch }},
                    {% if ajax is defined %}'ajax': '{{ ajax }}',{% endif %}
                    'search': {
                        'caseInsensitive': {{ caseInsensitive }}
                    }
                })
            });
            {% if tableCheckboxes %}
                require(['core/dt-checkboxes'], function () {
                    $('.datatable').add_checkboxes();
                });
            {% endif %}
        </script>
    {% endif %}
{% endblock %}

Resources/views/generic_list.html.twig
{% extends "TisseoCoreBundle::container.html.twig" %}

{% block content %}
    <table class="table {% block table_classes %}table-hover{% endblock %}">
        <thead>
            <tr>
               {% block table_head %}{% endblock %}
            </tr>
        </thead>
        <tbody>
            {% block table_body %}{% endblock %}
        </tbody>
    </table>
    {% block list_pagination %}{% endblock %}
{% endblock %}

Resources/views/macros.html.twig
{% macro line_number(object, type, size) %}
    {% if type == 'lineVersion' %}
        {% if object.line.number %}
            {% if size == 'small' %}
        <div class="line-number line-small" style="color:{{ object.fgColor.html }}; background-color:{{ object.bgColor.html }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'big' %}
        <div class="line-number line-big" style="color:{{ object.fgColor.html }}; background-color:{{ object.bgColor.html }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'free' %}
        <div class="line-number line-free" style="color:{{ object.fgColor.html }}; background-color:{{ object.bgColor.html }}; font-family:sans-serif; font-weight: bold;">
            {% endif %}
            <span>{{ object.line.number }}</span>
        </div>
        {% endif %}
    {% elseif type == 'line' %}
        {% if object.LastLineVersion %}
            {% set lineVersion = object.LastLineVersion %}
            <div class="line-number line-{{ size }}" style="color:{{ lineVersion.fgColor.html }}; background-color:{{ lineVersion.bgColor.html }}; font-family:sans-serif; font-weight: bold;">
        {% else %}
        <div class="line-number line-{{ size }}" style="font-family:sans-serif; font-weight: bold;">
        {% endif %}
                <span>{{ object.number }}</span>
            </div>
    {% elseif type == 'api' %}
        {% if object.shortName %}
            {% if size == 'small' %}
                <div class="line-number line-small" style="color:{{ object.fgXmlColor }}; background-color:{{ object.bgXmlColor }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'big' %}
                <div class="line-number line-big" style="color:{{ object.fgXmlColor }}; background-color:{{ object.bgXmlColor }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'free' %}
                <div class="line-number line-free" style="color:{{ object.fgXmlColor }}; background-color:{{ object.bgXmlColor }}; font-family:sans-serif; font-weight: bold;">
            {% endif %}
            <span>{{ object.shortName }}</span>
        </div>
        {% endif %}
    {% elseif type == 'tad' %}
        {% if object.lineCode %}
            {% if size == 'small' %}
                <div class="line-number line-small" style="color:{{ object.fgColor }}; background-color:{{ object.bgColor }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'big' %}
                <div class="line-number line-big" style="color:{{ object.fgColor }}; background-color:{{ object.bgColor }}; font-family:sans-serif; font-weight: bold;">
            {% elseif size == 'free' %}
                <div class="line-number line-free" style="color:{{ object.fgColor }}; background-color:{{ object.bgColor }}; font-family:sans-serif; font-weight: bold;">
            {% endif %}
            <span>{{ object.lineCode }}</span>
        </div>
        {% endif %}
    {% endif %}
{% endmacro %}

{% macro line_version_date(lineVersion, dateType) %}
    {% if lineVersion.status == "new" %}
        <span class="line-version-date label label-info">{{ attribute(lineVersion, dateType)|date('d/m/Y') }}</span>
    {% elseif lineVersion.status == "published" %}
        <span class="line-version-date label label-success">{{ attribute(lineVersion, dateType)|date('d/m/Y') }}</span>
    {% endif %}
{% endmacro %}

{% macro pattern(pattern) %}
    <span>
        {% for day in pattern %}
        <span class="{% if day %}green-fg-day{% else %}red-fg-day{% endif %}">{{ ('tisseo.global.short_days.'~loop.index)|trans }}</span>
        {% endfor %}
    </span>
{% endmacro %}

{% macro line_api_number(line) %}
    <span class="api-line"
          style="color:{{ line.fgXmlColor}}; background-color:{{ line.bgXmlColor}};">
        {{ line.shortName }}
    </span>
{% endmacro %}

{% macro checkbox(line, isToggle = false) %}
    <input type="checkbox" class="checkbox" data-id="{{ line.id }}" {% if isToggle %}id="checkbox-toggle"{% endif %}">
{% endmacro %}